server:
  port:8080
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_system
    username: postgres
    password: admin
    hikari:
      maximumPoolSize: 15
  jpa:
    show_sql: true
    format_sql: true
    database-paltform: org.hybernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
